### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by iAmEben**

### CODE REVIEW

**Review by atakangah — COMMENTED** [review]
Great. The registration interface is good. But I think you only designed for Staff. The Student Registration Fragment is not yet done. Correct me if I'm wrong ok.

**Comment by atakangah** [comment]
Conflict resolution needed for this commit. Or things are ok now?

**Comment by iAmEben** [comment]
Kindly get the updated codes from the master branch... It's finished.
Pushed some hours ago

**Comment by atakangah** [comment]
> Kindly get the updated codes from the master branch... It's finished. Pushed some hours ago
Ok great. Then I'll approve the pull request so that it can get merged into master for things to look cleaner.

**Review by atakangah — APPROVED** [review]

**Comment by iAmEben** [comment]
Okay clone and tell me if it's updated or not cause I was having issues
from my end then it finally went through.

**Pull request closed without merging**
